export const SET_CURRENT_USERS="SET_CURRENT_USER";

export const CHANGE_LOGIN_STATE="CHANGE_LOGIN_STATE";

export const GET_USER_DATA="GET_USER_DATA";

export const GET_ARTICLE_DATA="GET_ARTICLE_DATA";